### ISSUE TITLE
no build artifact for duckdb v0.10.0

### ISSUE THREAD

**Issue by srenatus** [ywelsch/duckdb-prql#11]
Heya! Thanks for sharing this extension. I've noticed that it'll fail when installing with duckdb v0.10.0 ([released last week](https://github.com/duckdb/duckdb/releases/tag/v0.10.0)):

```
$ duckdb -unsigned      
v0.10.0 20b1486d11
Enter ".help" for usage hints.
D SET custom_extension_repository='http://welsch.lu/duckdb/prql/latest';
D FORCE INSTALL prql;
Error: HTTP Error: Failed to download extension "prql" at URL "http://welsch.lu/duckdb/prql/latest/v0.10.0/osx_amd64/prql.duckdb_extension.gz"

Candidate extensions: "parquet", "sqlite", "sqlite3", "sqlite_scanner"
D 
```
presumably because it hasn't been built for v0.10.0, as [the extension repo](http://welsch.lu/duckdb/prql/latest/) only contains tarballs up to v0.9.2.

One workaround is to grab the duckdb v0.9.2 binary from the releases page and use that -- and the installation instructions work flawlessly ✨ 

Would it be possible to add 0.10.0 to the artifacts that are built? Are they built automatically, so that I can open a PR of some sort to help with this...? 🤔

**Comment by ywelsch** [comment]
I've pushed support for 0.10.0 in https://github.com/ywelsch/duckdb-prql/pull/13

The binaries should be available in 30 minutes.
