### ISSUE TITLE
Error when compiling extension

### ISSUE THREAD

**Issue by tobilg** [ywelsch/duckdb-prql#3]
I was trying to do a custom compilation for the prql extension, but I'm seeing the following error during the build:

```bash
#8 1039.2 [ 62%] Building CXX object extension/prql/CMakeFiles/prql_extension.dir/src/prql_extension.cpp.o
#8 1039.3 /tmp/from-git/duckdb-prql/src/prql_extension.cpp:12:12: fatal error: libprql_lib.h: No such file or directory
#8 1039.3    #include "libprql_lib.h"
#8 1039.3             ^~~~~~~~~~~~~~~
#8 1039.3 compilation terminated.
#8 1039.3 gmake[3]: *** [extension/prql/CMakeFiles/prql_extension.dir/src/prql_extension.cpp.o] Error 1
```

Could you give me a hint on how to fix this? Thanks in advance @ywelsch!

**Comment by ywelsch** [comment]
I assume that your custom compilation involved upgrading the prql dependency to v0.6.1 (which leads to the above error as some code moved around in the prql repo). If that's the case, providing that context would have been helpful. In any case, I've just pushed an update (https://github.com/ywelsch/duckdb-prql/commit/2dffc54bce1a20fdaf8f9dcc26834f01aa2c9703) that does the upgrade to v0.6.1.

**Comment by tobilg** [comment]
Thanks, I didn’t change anything except running the git submodules commands before make, because that didn‘t work initially… I assume that this is the reason. 

Will try another build tomorrow, and will follow up here. Thanks again!

**Comment by tobilg** [comment]
Thanks again @ywelsch, it works now!

**Comment by ywelsch** [comment]
Perfect, thanks for letting me know! 👍
