### ISSUE TITLE
Installation on Windows ?

### ISSUE THREAD

**Issue by jgranduel** [ywelsch/duckdb-prql#7]
Hi, 

I wanted to give a try to prql in duckdb on a Windows-10 laptop (duckdb-0.8.1).
I couldn't install it. Here are the steps:

```
> duckdb -unsigned
v0.8.1 6536a77232
Enter ".help" for usage hints.
D SET custom_extension_repository='welsch.lu/duckdb/prql/latest';
D FORCE INSTALL prql;
Error: HTTP Error: Failed to download extension "prql" at URL "http://welsch.lu/duckdb/prql/latest/v0.8.1/windows_amd64/prql.duckdb_extension.gz"

Candidate extensions: "parquet", "sqlite", "sqlite3", "sqlite_scanner"
D
```

Should it be possible as of now ? prql cli compiler works on Windows...

**Comment by ywelsch** [comment]
Hi @jgranduel, building the duckdb-prql plugin for duckdb 0.8.1 on windows was indeed [broken](https://github.com/ywelsch/duckdb-prql/actions/runs/5749966337/job/15585796020). I did spent some time trying to figure out why that is the case (linker issues) when releasing duckdb-prql for 0.8.1, but it was not clear to me where the issue was coming from (it worked in earlier releases). Upgrading the dependencies now (prqlc from 0.9.3 to 0.9.4 and corrosion, the CMake Rust integration that I'm using) looks to have fixed the issue though. Give it another try and let me know if it now works.

**Comment by jgranduel** [comment]
Thanks for your answer.
I have tried again. It went better, but I am still noticing things that I want to report.

I could install a first time, but another trial gave me this error. Probably Windows only

```
> duckdb.exe -unsigned
v0.8.1 6536a77232
Enter ".help" for usage hints.
D SET custom_extension_repository='welsch.lu/duckdb/prql/latest';
D FORCE INSTALL prql;
Error: IO Error: Could not move file: Impossible de créer un fichier déjà existant. (impossible to create an existing file)

D load prql;
> -- seems OK
```
I removed extenstions from `~/.duckdb/extensions/v0.8.1/windows_amd64`
```
-a---          2023-09-06    09:36       21632000 prql.duckdb_extension
-a---          2023-09-06    09:41       21632000 prql.duckdb_extension.tmp-0fa5bddd-36f7-44aa-9b35-ce707671d01d
-a---          2023-09-06    09:45       21632000 prql.duckdb_extension.tmp-8f4eacf3-d03f-44a7-9e28-bda6e963299f
```
Indeed, `FORCE INSTALL` doesn't work on Windows as it leaves `prql.duckdb_extension.tmp-xxx` extensions

I made another simple test which gives me unexpected results (I'm just playing with PRQL, so might be my mistakes).

```
> duckdb.exe -unsigned
v0.8.1 6536a77232
Enter ".help" for usage hints.
D create table t (name text, age int, primary key(name));
D insert into t values('bob', 20);
D from t;
┌─────────┬───────┐
│  name   │  age  │
│ varchar │ int32 │
├─────────┼───────┤
│ bob     │    20 │
└─────────┴───────┘

D load prql;
D from t
> filter name == 'bob';
┌─────────┬───────┐
│  name   │  age  │
│ varchar │ int32 │
├─────────┼───────┤
│ bob     │    20 │
└─────────┴───────┘
D from t | filter name  == 'bob' | derive [ a = 10,  age10 = age + a, ];
Error: Parser Error: Error:
   ?─[:2:60]
   │
 2 │ from t | filter name  == 'bob' | derive [ a = 10,  age10 = age + a, ]
   │                                                            ───┬───
   │                                                               ?───── array expected type `int`, but found type `int || float || timestamp || date`
───?
```
 Is it a duckdb or prql extension issue?

**Comment by ywelsch** [comment]
Re force install issue: The install should only be done the very first time, i.e., it's not recommended to run this command every time you run duckdb, as it will redownload the extension from the custom repo. After an initial installation, just doing a `load prql` is enough (no need to set custom extension repository either then). Windows is known to have issues with overriding files (which is implemented atomically with temp file + move in DuckDB) when these files have been mapped into a process before. This is not an issue specific to my extension (but applicable to all extensions). An alternative is not to use **force** install, but just regular install. In that case it will skip the installation when the extension is already present.

Re parser error:
PRQL has recently changed the syntax from square brackets to curly brackets, see https://prql-lang.org/book/reference/stdlib/transforms/derive.html

The example works if you write `from t | filter name  == 'bob' | derive { a = 10,  age10 = age + a, }`

**Comment by jgranduel** [comment]
Thank you.

Using `FORCE INSTALL` was just a test. I know it's a recurring issue on Windows.

Sorry for the syntax error. I read about the change from `[]` to `{}` in [release 0.9.0](https://github.com/PRQL/prql/releases/tag/0.9.0), but didn't think about it when testing, nor did I check the official documentation.
Would you mind updating your README.md that I was following blindly?

Thanks again!

**Comment by ywelsch** [comment]
> Would you mind updating your README.md that I was following blindly?

Thanks for pointing out the out-of-date README - I've updated it now.
